### ISSUE TITLE
각 서비스별 bound 결정하기

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#111]
- [x] consensus
- [x] blockchain
- [x] peer
- [x] txpool
- [ ] authentication
- [x] smartcontract

각자 관심있는 서비스의 bound를 정하고 README.md에 정리하여 풀리퀘 보내주세요!

**Comment by byron1st** [comment]
bound를 정한다는게 어떤 말인가요?

**Comment by junbeomlee** [comment]
명확하게
서비스의 범위를 정한다는 의미로 사용하였습니다.
이 서비스의 범위와 서비스의 범위가 아닌것을 정한다는 의미입니다.
