### ISSUE TITLE
go src 구조 변경

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#112]
기존 멤버들은 
프로젝트의 구조가 src/it-chain -> src/github.com/it-chain/it-chain-Engine으로 바뀌었음
기존의 src/it-chain은 지우고(**꼭 지워야함**) 

src/github.com/it-chain/it-chain-Engine위치에 git clone하거나 
go get github.com/it-chain/it-chain-Engine으로 새로 받아서 작업하세요!!

처리되면 답글달아주삼 모두 달면 close하겠음

**Comment by yojkim** [comment]
저는 세팅하였습니다.

**Comment by junbeomlee** [comment]
close할께요!!
