### ISSUE TITLE
implementation details 영어 -> 한글 번역

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#114]

**Comment by owljoa** [comment]
안녕하세요 :) 
한글로 번역된 파일을 따로 생성하는건가요?

**Comment by junbeomlee** [comment]
어떻게 하면 좋을까요?! 따로 파일을 유지하거나 append해서 할 수도 있을 것 같은데, 파일을 따로 하는것이 좋을 것으로 보입니다. 더 좋은 아이디어가 있으시면 부탁드립니다. 
implementation details분할 작업도 해야하니 분할 하시고 번역해주시면 더 좋을 것 같습니다!

**Comment by zeroFruit** [comment]
혹시 아직 아무도 시작안하셨으면 1. BlockChain 부분 제가 맡아서 번역해봐도 괜찮을까요?

**Comment by junbeomlee** [comment]
먼저 말하고 시작하면 겹치지 않고 더 좋을듯 합니다!! 번역하면서 자세히 읽으면 코드를 이해하는것도 좋으니 굳굳이요

**Comment by codeblv** [comment]
그러면 제가 smart contract 부분 진행해볼게요!

**Comment by byron1st** [comment]
@junbeomlee 
파일 이름 뒤에 _KR 형태로 붙여서 구분해주면 어떨지요? 예를 들어, `PROJECT_IMPLEMENTATION_DETAILS.md` 는 `PROJECT_IMPLEMENTATION_DETAILS_KR.md` 과 같이 구분해주면, 향후 번역이 추가되더라도 언어별로 구분도 할 수 있을 것 같습니다.

**Comment by byron1st** [comment]
제가 Consensus 부분을 하겠습니다.

**Comment by zeroFruit** [comment]
blockchain 부분 번역을 완료했는데요.
풀리퀘를 날리려고하는데 브랜치를
features/translation
features/translation/[각자가 맡은 파트] <= blockchain, smart_contract ...
로 만들어서
features/translation/[각자가 맡은 파트] => features/translation로 풀리퀘를 날리는 방식은 어떤가요?

**Comment by junbeomlee** [comment]
features/translation에서 develope으로 한번더 옮겨야 하고 너무 많은 브런치가 생길수도 있다는 생각이 들어서 문서는 그냥 docs라는 브런치 혹은 블록체인 부분이니 features/blockchain쪽에서 풀리퀘를 날리는방식을 취하고 pull request메세지에 설명을 넣는방식은 어떨까 합니다!!

**Comment by zeroFruit** [comment]
docs가 좋아보이네요!

**Comment by junbeomlee** [comment]
documentation파트는 docs/[각자 맡은 파트]로 진행 할께요!!
이게 풀리퀘가 남아있으면 푸쉬된걸 추적해 버리네요!!

**Comment by zeroFruit** [comment]
docs/[각자 맡은 파트]로 브랜치를 만들면 브랜치 이름이 invalid 하다고 나오네요.
이미 docs 라는 브랜치가 있어서인 것 같습니다.

**Comment by junbeomlee** [comment]
docs를 없애고 docs/readme로 새로 풀리퀘 보낼께요!

**Comment by codeblv** [comment]
@ #121 
번역을 하다보니 번역 범위나 용어 선택에서 생각해볼 문제가 생겼습니다.

**Comment by owljoa** [comment]
crypto 부분을 제가 해보겠습니다.

**Comment by rla1219** [comment]
database 부분은 제가 하겠습니다.

**Comment by junbeomlee** [comment]
완료된것 같으니 close하겠습니다!
