### ISSUE TITLE
README에 Usage 추가

### ISSUE THREAD

**Issue by zeroFruit** [it-chain/it-chain-Engine#115]
아직 golang에 익숙하지않아서요.

깃풀받아서 한번 돌려보고싶은데 어떻게 실행시키는지 잘 모르겠어요.

그래서 README에도 어떻게 사용하는지 간단하게 사용법을 명시하는 건 어떨까 제안해봅니다!

**Comment by byron1st** [comment]
동의합니다. 루트에 있는 README에 installation, run 예를 넣어주는게 좋겠네요.

**Comment by junbeomlee** [comment]
closed
