### ISSUE TITLE
번역과정에서 한글화의 범위와 용어선택

### ISSUE THREAD

**Issue by codeblv** [it-chain/it-chain-Engine#121]
번역을 하다보니 어디까지 한글화를 해야하는지가 조금 고민입니다.
Smart Contract -> 스마트 컨트랙트
Docker -> 도커
Git Repository -> 깃 저장소
이렇게까지 한글화를 하는 게 나은지 아니면 그냥 영문 표현을 쓰는 게 나은지 고민이 되네요.

@junbeomlee  @byron1st  @zeroFruit

**Comment by owljoa** [comment]
스마트 컨트랙트를 예로 들면, 처음 표현할때 스마트 컨트랙트(Smart Contract)라고 명시하고 이후에는 스마트 컨트랙트라고 표현하는것이 어떨까요?

**Comment by junbeomlee** [comment]
개인적으로 위의 단어들은 영문 표현을 쓰는것이 더 좋다고 생각이 드네요!

**Comment by codeblv** [comment]
적당히 판단해서 해보아야겠어요. 다만 번역 다 끝나고 나서 문서를 누가 한 번 총괄해서 검수할 필요는 있을 거 같네요.

**Comment by byron1st** [comment]
개인적으로 Git과 Docker는 영어를 그냥 쓰는게 나아 보이고, Smart Contract은 @owljoa 님의 의견에 동의합니다. 다만 블록체인의 일반적인 스마트 컨트랙트 이야기를 하는게 아니라, `it-chain` 아키텍처의 구성요소인 Smart Contract Service를 말하는 것이라면 영문을 적는 것이 좋을 것 같네요. 아키텍처의 다른 구성요소들(i.e. 서비스들)은 Peer Service, Consensus Service 이런식으로 영문 명시를 하고 코드에도 영문으로 나오게 될 것이기 때문입니다.
