### ISSUE TITLE
it-chain Readme사진 수정

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#125]
![main-image](https://user-images.githubusercontent.com/10362293/37346715-683154fc-2713-11e8-99ea-03d26b36094d.png)

Readme 사진 이걸로 수정하자고 하네여 저는 좋은듯!!

**Comment by codeblv** [comment]
로고 밑에 글씨 들어가게 바뀐 거죠? 저도 이거 좋은 거 같아요!

**Comment by junbeomlee** [comment]
넵

**Comment by junk-sound** [comment]
좋습니당~

**Comment by junbeomlee** [comment]
close하겠습니다.
