### ISSUE TITLE
develop 및 feature/ 브랜치 생성

### ISSUE THREAD

**Issue by zeroFruit** [it-chain/it-chain-Engine#134]
슬슬 코드를 보려고 하는데 그 전에
#109 와 관련된 이야기를 픽스하고 브랜치를 생성하면 좋을 것 같습니다!

**Comment by junbeomlee** [comment]
개발하고싶은 서비스를 정하고 그 서비스의 범위에 대해서 같이 논의하면 좋을 것 같습니다. 
완전히 픽스를 할 수는 없을 것 같고 제 consensus작업처럼 관심있고 개발하고싶은 서비스의 내용을 정리해서 올려주시면 같이 얘기해봐요!

**Comment by zeroFruit** [comment]
저는 일단 legacy에 있는 @emperorhan 님께서 작업하셨던 blockchain 부분을 코드도 공부할겸 DDD로 옮겨보려고합니다!

**Comment by byron1st** [comment]
@junbeomlee 님, feature/ 브랜치랑 docs/ 브랜치는 자유롭게 만들더라도, @zeroFruit 님 말씀대로, #109 내용 중 develop 브랜치를 운영할 것인지 여부를 결정하고, 운영한다면 develop 브랜치 정도는 우선 만들어주는 것이 좋을 것 같습니다.

만약 develop 브랜치를 운영한다면, feature/ 브랜치는 pull request를 develop으로 던지게끔 규칙을 정하는 것이 좋을 것 같네요.

**Comment by junbeomlee** [comment]
develop브런치 추가하도록하겠습니다!
