### ISSUE TITLE
it-chain install 문제

### ISSUE THREAD

**Issue by zeroFruit** [it-chain/it-chain-Engine#135]
### Actual Behavior
![image](https://user-images.githubusercontent.com/18715362/37593732-570db0a6-2bb6-11e8-9036-c583ff02fc22.png)

### Steps To Reproduce Behavior
* git pull origin master
* go get

git pull 후에 go get 을 하니 에러가 뜨네요 :(
혹시 도움을 주실 수 있을까요?

**Comment by junbeomlee** [comment]
거기서 go get 하는거 아닙니다.
go get 은 라이브러리 다운받는거고 go get github~~로 하는 커맨드입니다!

**Comment by zeroFruit** [comment]
![image](https://user-images.githubusercontent.com/18715362/37595152-100d9ae0-2bbb-11e8-84f6-acb2a4726755.png)

go run main.go 를 했을때의 화면입니다 :(

**Comment by zeroFruit** [comment]
제 프로젝트 위치가 잘못됐었습니다.
$GOPATH에서 go get github.com/it-chain/it-chain-Engine을 해주니 해결되었습니다 👍
