### ISSUE TITLE
SmartContractService 구조 초안

### ISSUE THREAD

**Issue by hackurity01** [it-chain/it-chain-Engine#136]
![image](https://user-images.githubusercontent.com/8624075/37662919-70b1974e-2c9b-11e8-8d41-b26b8dc9b3e2.png)

현재 구상 중인 SmartContractService 구조의 그림입니다.
아직 확실하게 구조를 잡거나 구체적인 내용이 나온건 아니지만 피드백 사항이 있을까 해서 공유합니다.

**Comment by junbeomlee** [comment]
스켈레톤 코드와 스마트컨트랙의 관심 data, primary data의 정의를 다음 Step으로 하면 좋을 것 같습니다!

**Comment by byron1st** [comment]
concern을 분리한 것은 좋습니다. 다만, 그림에서 몇가지 질문 사항이 있는데요,

1. MsgInterface와 MsgAPI는 어떤 점이 다른 것인가요?
2. 각 박스는 Package 인가요? 만약 그렇다면, 실제 코드 폴더구조에도 동일하게 반영이 되면 이해하기 좋을것 같습니다.
3. (박스가 Package라는 전제 하에) 각 Package 사이의 참조관계(함수 콜, type 참조 등)가 어떻게 되는지 설계를 해주면 좋을 것 같습니다. 예를 들어, SmartContractAPI는 ContainerAPI를 참조하지만, ContainerAPI는 SmartContractAPI를 참조하지 않는다던지 하는 관계들입니다.

좋은 출발이네요!
