### ISSUE TITLE
Blockchain 서비스 Context Boundary 논의

### ISSUE THREAD

**Issue by zeroFruit** [it-chain/it-chain-Engine#141]
# Blockchain

각 P2P Network 구성원들의 블럭들을 조회, 검증할 수 있다. 합의 이전에는 아직 합의가 안된 블럭들을 저장(생성)하고 합의 과정에는 합의된 블럭들을 저장(생성)한다. 

## Primary Data

* 블럭
* 트랜젝션
* 머클트리

## Consume Event

* 합의 이전 블럭들을 추가
* 합의된 블럭들을 추가

## Publish Event

* 블럭 조회
* 블럭 검증

--------------------

사람이 많은만큼 대화채널을 빨리 만드는 것이 좋을 거 같아서 이슈를 올려보았습니다.
아키텍쳐가 바뀌면서 다른 서비스들과 관계 속에서 Blockchain 서비스가 어디까지의 역할을 맡을지를 먼저 생각해보면 좋을 거 같았습니다.
내용들을 엄청 뭉뚱그려 적었고 용어도 일부러 일단은 한글로 다 작성했습니다. 포멧은 일단 @junbeomlee 님께서 작성해주신 Consensus부분을 따랐습니다.

> 각 P2P Network 구성원들의 Block들을 조회, 검증할 수 있다. 합의 이전에는 아직 합의가 안된 Block들을 저장(생성)하고 합의 과정에는 합의된 블럭들을 저장(생성)한다. 

이 부분은 제가 생각한 Blockchain 서비스의 Boundary입니다.(오류가 있을수 있습니다!ㅎㅎ) 각자 생각한 것들을 올리면서 같이 고쳐나가면 좋을 것 같습니다!

**Comment by junbeomlee** [comment]
좋은 시작으로 보입니다. 

각 P2P Network 구성원들의 Block들을 조회, 검증할 수 있다. 합의 이전에는 아직 합의가 안된 Block들을 저장(생성)하고 합의 과정에는 합의된 블럭들을 저장(생성)한다. 
->
블록체인에 저장할 Block을 생성 및 검증, 블록체인의 Block을 조회 및 동기화를 할 수 있다. 는 어떤가요?
(블록체인서비스는 P2P Network와는 상관없이 블록체인 자체에 포커스를 두기 때문에 설명에 넣지 않는편이 더 좋은 것 같습니다. 그리고 동기화에 대한 얘기가 빠졌는데 이부분도 중요한 issue인것 같습니다. 나중에 노드가 Network에 참여 할 경우 다른 노드의 블록체인과 동기화를 진행해야 합니다.)

## Primary Data
머클트리는 블록에 포함되는 데이터이며 블록에 많이 의존적인 Data이기 때문에 따로 관리한다는 것 보다는
Block과 Transaction 2개로 하는 것이 저는 더 좋은 방법인것 같습니다.

## Consume Event
**합의 이전 블럭들을 추가** 여기서 합의 이전에 블록들을 추가할 필요가 있는지 한번 생각을 해봐야 할 것 같습니다. 합의 이전에 블록들을 저장할 필요가 있는지에 대한 부분은 아직 명확하게 저도 저런 상황이 어떤 이유로 발생하고 왜 합의 안된 블록을 가지고 있어야하는지를 좀더 생각해보아야할 것 같습니다. 필요한 이유가 있다면 알려주세요!!

## Publish Event
블록의 생성이 빠져있는것 같고 몇가지 이벤트들이 더 필요할 것 같습니다. 같이 얘기해보면 찾을 수 있을것 같습니다!!


아주 좋은 출발이고 다른 분들도 같이 의견주시면 좋을 것 같습니다. 서로 피드백하며모두가 같은 방향 과 모델을 가지는 것이 중요하다고 생각합니다.

**Comment by junk-sound** [comment]
확인하였고, 참고하여 오늘 새벽까지는 저도 뭔가를 이슈에 올려보겠습니다.

**Comment by zeroFruit** [comment]
@junbeomlee 
1. 소개 부분에서 다른 서비스의 언급을 빼는 것은 좋은 것 같습니다. 처음에 Consume/Publish Event들에 대해서 생각하다보니 다른 서비스에 대한 언급을 했었던 것 같습니다.

2. **Consume Event**의 **합의 이전 블럭들을 추가**한다는 부분은 제가 블록체인의 동작을 제대로 이해를 못했던 것 같습니다.
합의 이전에 각 피어들이 다른 블록들을 가지고 있는 것이 아닌가요? 그리고 합의를 한 후에 모든 피어들이 같은 순서의 블록들을 가진다고 생각해서 **합의 이전 블럭들을 추가**한다는 부분을 적었었습니다.

3. 그리고 yggdrasill 라이브러리와의 경계도 개인적으로 궁금합니다. it-chain-Engine에서 blockchain서비스는 yggdrasil의 wrapper정도로 생각하면 좋을까요? (동기화부분은 따로 구현해야할 거 같기도 합니다)

**Comment by junbeomlee** [comment]
2번에서 합의 이전에는 피어가 합의된 블록들만 가지고 있으며, 리더가 합의할 블록을 만들고 합의가 완료되면 합의된 블록을 블록체인에 저장합니다. 각 피어들이 합의중인 블록을 임시로 가지고 있기는 하지만 합의된 블록들만 가지고 있다고 보는게 맞을 것 같습니다. 합의 이전 블록이라는게 1) 합의가 안된 블록 or 2) 블록체인 어떤것을 의미하는 건가요? 저는 1)번이라고 생각해 답변 달았습니다! 2)번 이라고하면 합의 이전이라는 표현이 합의되지 않은 으로 해석 되서 다른 표현이 좋을 것 같습니다!

3번에서 저도 아직 명확하게 구분하지는 못했습니다. 이부분은 같이 맞춰나가면 좋을 것 같은데 yggdrasill은 block저장소, 검증소 라고만 보면 될 것 같습니다. 이외는 모두 blockchain서비스에서 구현되야 할 것 같습니다. 동기화 같은 부분들도 blockchain서비스의 영역이라는 것에 동의합니다!

@zeroFruit

**Comment by junk-sound** [comment]
Publish event에 거래의 생성, 조회, 검증을 추가하는게 어떨까요? @zeroFruit @junbeomlee

**Comment by zeroFruit** [comment]
@junk-sound 거래란 것은 어떤 거래를 말하는 건가요??

**Comment by zeroFruit** [comment]
# Blockchain

블록체인에 저장할 Block을 생성, 조회 및 검증할 수 있다. Block을 구성하고 있는 Transaction이 정당한지 검증할 수 있다. 다른 블록체인과 자신의 블록체인을 동기화할 수 있다.


## Primary Data

* Block
* Transaction

## Consume Event


## Publish Event
* CreateNewBlock
* CreateNewTransaction
* AddBlock
* PutTransaction
* SetTxMethodParameters
* SetTxData
* GetBlockBy~
* VerifyBlock
* VerifyTx
* SyncBlockchain

--------------
계속 생각하다보니 blockchain 서비스에서는 block을 가지고 할 수 있는 것들이랑 block을 이루는 transaction가지고 할 수 있는 것들이랑 blockchain가지고 할 수 있는 것들을 하면 좋겠다고 생각했습니다.

> Block을 구성하고 있는 Transaction이 정당한지 검증할 수 있다.

그래서 transaction과 관련된 이야기를 추가했고

> 다른 블록체인과 자신의 블록체인을 동기화할 수 있다.

동기화 문제는 나중에 어떻게 구현될까 생각해보다가 다른 피어의 블록체인과 자신의 블록체인을 비교하는 방식으로 구현될 것 같아서 이렇게 적었습니다.

**Consume Event**들은 위에 코멘트대로 빼고나니 잘 생각이 안나네요. 아이디어 부탁드립니다

**Publish Event**는 legacy 코드들을 참고했습니다. Blockchain, Block, Transaction 레벨에서 다른 서비스들에게 필요할 법 해보이는 것들을 일단 죽 적어봤습니다.

**Comment by junk-sound** [comment]
@zeroFruit 블록에 새로 추가되는 거래들을 말한 것이었습니다!

수정된
"블록체인에 저장할 Block을 생성, 조회 및 검증할 수 있다. Block을 구성하고 있는 Transaction이 정당한지 검증할 수 있다. 다른 블록체인과 자신의 블록체인을 동기화할 수 있다."
에 동의하고 좋은 것 같습니다.

수정된 Publish event에서
SetTxMethodParameters, SetTxData는 CreateNewTransaction에서 사용되니 중복 방지를 위해 PublishEvent에서는 제외하고,  
VerifyTx는 VerifyBlock에서 사용되는 함수이니 legacy/domain/transaction의 validate를 이름만 바꿔 ValidateTransaction으로 대체하면 어떨까 싶습니다.

또 순서를 블록체인, 블록레벨, 트랜잭션에서 수행되는 이벤트로 정렬하는 것이 좋지 않을까 생각합니다.
예를 들어,
[블록체인레벨 수행]
CreateNewBlock
AddBlock
GetBlockBy
SyncBlockchain
[블록레벨에서 수행]
CreateNewTransaction
PutTransaction
VerifyBlock
[트랜잭션레벨에서 수행]
ValidateTransaction

**Comment by junbeomlee** [comment]
@junk-sound 거래라는 표현보다는 트랜잭션이라고 부르는것이 맞을것 같습니다. 비트코인에서는 transfer지만 여기서는 이 트랜잭션이 꼭 거래에 한정된 것은 아니고 스마트컨트랙의 실행요청이기 때문입니다!!

ConsumeEvent는 블록체인 서비스가 관심을 가지는 Event고
PublishEvent는 블록체인 서비스가 발행하는 Event입니다.

지금약간 섞여있는 것 같아서 이런식으로 Consume과 Publish Event를 구분해야 할 것 같습니다.
1. ReadyToAddBlock은 ConsumeEvent로 (외부로 부터 Block을 저장해 달라는 요청에 관한 이벤트)
2. BlockAdded은 PublishEvent이런식으로 가야할 것 같습니다. (블록체인 서비스가 블록을 성공적으로 저장해서 새로운 블록이 저장됬다는 이벤트)
위의 Event이름은 막 지었습니다.. 형식을 정해야할 듯!!

그리고 PutTransaction, SetTxMethodParameters, SetTxData이런 부분은 txpool에서 처리될 것 같습니다. 클라이언트가 txData를 노드에게 보내면 txpool이 받아서 가지고 있다가 리더가 보관하고있는 txData로 block을 만드는 것이기 때문에 필요한 부분은 아닌것 같습니다.

**Comment by junk-sound** [comment]
@junbeomlee 네 알겠습니다 설명 감사드립니다!!

**Comment by zeroFruit** [comment]
1. 그렇군요. **(1)** Transaction 생성과 **(2)** block을 만들기 위해 준비하는 부분들은 txpool로 넘어가는군요.

2. 그러면 말씀하신대로 리더가 가지고 있는 txData들을 block으로 만들 때 
**(1)** blockchain 서비스에 block을 생성해달라는 event가 필요할 거 같아요. 
그리고 **(2)** block을 blockchain에 추가해달라는 event가 하나 더 있어야 할 거 같고요.
또 **(3)** block과 관련된 정보를 조회하는 event는 그대로 있어야할 거 같아요.

3. event 네이밍 형식은 먼저 **(1)** ConsumeEvent부터 ReadyToAddBlock도 괜찮은 거 같고(정말 막 지은거 맞나요?ㅋㅋ) 제가 떠오른것은 RequestToAddBlock? 정도 입니다.
마찬가지로 ReadyToCreateBlock(RequestToCreateBlock), 조회부분에서는 ReadyToFind~, **(2)** PublishEvent는 네이밍에 성공여부가 들어갔으면 좋겠어요. 그래서 BlockAddSuccess/Fail, BlockFindBy-Success/Fail 등등..
