### ISSUE TITLE
3/31 Dead line

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#142]
it-chain offline 미팅 때 얘기되었던 각자의 이번주 목표에대해 올리고 완료하신 분들은 체크박스 눌러주시면 됩니다!
모두 완료했을 경우 close하겠습니다. 그날 참여하지 못했지만 이번주 목표가 있으신 분들은 댓글로 남겨주시면 추가하겠습니다.

- [x] @yojkim heimdall packaging, hash까지 
- [ ] @hackurity01 DDD개념 Modeling
- [ ] @luke9407 yggdrasill library완성 및 documentation
- [ ] @zeroFruit blockchain 서비스 유비쿼터르 랭귀지와 modeling
- [x] @owljoa heimdall function input,output 정리 
- [ ] @junk-sound blockchain 서비스 유비쿼터르 랭귀지, go 공부
- [x] @junbeomlee bifrost완성, consensus 완성

**Comment by junk-sound** [comment]
네 알겠습니다~

**Comment by junbeomlee** [comment]
ㅠㅠ 저는 아직 미완.. 오늘 마무리해서 완료 하겠습니다.

**Comment by junbeomlee** [comment]
얼른 마무리해주세요!!! ㅋㅋㅋㅋ
