### ISSUE TITLE
오프라인에서 말씀드린 코멘트에 대한 제안인데 의견이 다를수도 있을것 같아서 등록합니다!

### ISSUE THREAD

**Issue by owljoa** [it-chain/it-chain-Engine#143]
제가 주로 사용하던 파이썬에서는 아래와 같은 코멘트를 다는 것이 convention이였습니다.
인텔리제이 기반 파이참에서 주석 생성시 함수 원형을 보고 자동으로 저렇게 :param 같은 것들이 만들어집니다.
저런 표준방식의 코멘트가 좋은점은 tool(파이썬의 경우는 sphinx)을 이용한 자동 documentation을 할 때,
편합니다. 그리고 tool까지 안가더라도 코드를 나중에 읽어도 눈에 잘 들어오고요 :)

def load_data(p_user_id: str, target_dir: str, only_user_data: bool=False, fix_user_sample: int=None, fix_imposter_sample: int=None) 
-> [np.ndarray, np.ndarray] or np.ndarray:
"""
load legitimate user's data and imposters' data from csv files
:param p_user_id: legitimate user's id(initial)
:param target_dir: target directory for finding requested user data
:param only_user_data: if true, return user data only. if false, return user and imposter data
:param fix_user_sample: fix the number of legitimate user sample to return
:param fix_imposter_sample: fix the number of imposter sample to return
:return: legitimate user data and imposter data
"""

그런데 Go 언어의 convention을 보니 조금 다른것 같네요. golang 개발 깃헙 문서에는 아래와 같은 예시가 있었고, 링크로 가시면 부연설명도 있습니다.(링크 : https://github.com/golang/go/wiki/Comments)
godoc이라는 documentation 자동화 tool도 있네요. (https://godoc.org/)
한글버전의 comment 설명은 (https://golang.kr/doc/effective_go/commentary.html) 에서 조금 볼수 있네요.

// Package superman implements methods for saving the world.
//
// Experience has shown that a small number of procedures can prove
// helpful when attempting to save the world.
package superman

// enterOrbit causes Superman to fly into low Earth orbit, a position
// that presents several possibilities for planet salvation.
func enterOrbit() os.Error {
...
}

coding convention을 일일이 따르는건 나중에 해도 될것 같지만 코멘트나 문서에 대한 규칙(?)은 미리 정의해두어야 좋을것 같아서 제안을 드리고 제가 이번주에 해보겠다고 말씀은 드렸지만

생각해보니 토론이 필요할것 같기도 하고.. 제가 이번주는 아마 토요일에나 제대로된 작업을 할 수 있을것 같아서 그 사이 기간에 의견을 여쭤보려고 이슈 등록했습니다.

"매우 좋다!" 혹은 "이런 스타일의 코멘트를 다는것은 아직 이르다!"  혹은 "코멘트 다는것 자체가 아직은 이르다!" 등등 의견 부탁드립니다.

**Comment by owljoa** [comment]
golang math 패키지에서 빅넘버 연산에 대한 코드인데.. 위에 제가 너무 길게 드린 복잡한 설명보다 좋은 예시가 될 것 같습니다.

<코드>
https://github.com/golang/go/blob/release-branch.go1.5/src/math/big/int.go#L405

<godoc을 이용한 documentation 결과>
https://godoc.org/math/big#Int

**Comment by byron1st** [comment]
Go 언어는 코멘트 규칙이 엄격하지 않더라구요. 문서화하고자 하는 함수/타입 위에 `//` 표시하면, 위의 예제처럼 그냥 평문으로 출력되는 형태인 것으로 보입니다. 권장하는 사항은 함수 이름이 `getID`일 경우 주석은 `// getID returns ID value ..blah blah` 이런 식으로 문서화하고자 하는 함수/타입 이름으로 문서가 시작하게끔 하는 정도 인거 같습니다. 그리고 Export 되는 함수/타입들(대문자로 시작되는)은 반드시 코멘트 하는걸 권장하구요. 저희도 이정도부터 시작하면 좋은 출발이 될거 같습니다.

**Comment by junbeomlee** [comment]
@byron1st 님이 말씀하신대로 python과는 다르게 go는 함수 파라미터의 타입이 명시적으로 표기되어 있기 때문에 변수에 대한 설명보다는 대문자로 시작하는 즉 Export되는 변수 혹은 함수의 설명과 파일에 대한 전반적인 설명을 기준으로 하는것이 어떨까요?!!

**Comment by owljoa** [comment]
@byron1st @junbeomlee 두분 말씀처럼 필수적인 코멘트부터 시작하는 것이 좋을 것 같습니다! :) 

그럼 제 숙제 auth쪽 작성해서 좋은 예시 만들어보겠습니다.. 하하;
