### ISSUE TITLE
블록체인서비스-유비쿼터스랭기지 작성을 위한 내용 정리

### ISSUE THREAD

**Issue by junk-sound** [it-chain/it-chain-Engine#146]
아직 모르는 것이 많은데도 일단 작성한거라 틀린 부분도 많을 것이고, 정돈도 안된 느낌입니다.
그럼에도 불구하고 시간을 너무 끌다보면 진행이 안될 것 같아서 일단 올립니다.
내용 면에서 미완성이니 바쁘신 분들은 읽지 않으셨다가 다시 수정하면 그 때 읽어주시기 바랍니다.
다만 형식적인 면에서는 피드백을 주셨으면 좋겠습니다. 준범님의 블로그를 참고한 건데, 이런 형식이면 되는 것인지 확인해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/29854899/38230328-4db73c00-3748-11e8-847a-d689b9c5452b.png)

**Comment by junbeomlee** [comment]
글이 잘린것 같습니다!
