### ISSUE TITLE
it chain package path /it-chain -> githbub/junbeomlee/it-chain 

### ISSUE THREAD

**Issue by junbeomlee** [it-chain/it-chain-Engine#94]

**Comment by byron1st** [comment]
go 프로젝트를 가져오는 용도로 사용되는 go 디폴트 도구인 `go get` 도구는 프로젝트를 가져올 경우 `$GOPATH\src` 폴더에 배치합니다. 이때 현재 `it-chain`의 패스 경로가 `go get` 도구가 설치하는 경로와 맞지 않아서 패스를 resolve 하지 못하는 문제가 발생합니다. 스샷 참고하세요.

![2018-02-20 11 20 24](https://user-images.githubusercontent.com/1930352/36411119-5a0471a6-1657-11e8-9509-e14d918f8f76.png)

go 언어에서 패키지 패스의 de-facto 표준이 `go get`으로 가져오는 경로이므로, 이에 맞추는 것이 좋을 것 같네요.

**Comment by junbeomlee** [comment]
수정완료
